language: swift

osx_image: xcode10
xcode_workspace: BrickKit.xcworkspace

matrix:
   include:
      - 
        xcode_sdk: iphonesimulator12.0
        xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone SE
        xcode_scheme: BrickKit
      - 
        xcode_sdk: iphonesimulator12.0
        xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone SE
        xcode_scheme: BrickApp-iOS
      - 
        xcode_sdk: iphonesimulator12.0
        xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
        xcode_scheme: BrickKit
      - 
        xcode_sdk: iphonesimulator12.0
        xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
        xcode_scheme: BrickApp-iOS
      - 
        xcode_sdk: appletvsimulator12.0
        xcode_destination: platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p
        xcode_scheme: BrickKit-tvOS
      - 
        xcode_sdk: appletvsimulator12.0
        xcode_destination: platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p
        xcode_scheme: BrickApp-tvOS
      - 
        xcode_sdk: appletvsimulator12.0
        xcode_destination: platform=tvOS Simulator,OS=12.0,name=Apple TV
        xcode_scheme: BrickKit-tvOS
      - 
        xcode_sdk: appletvsimulator12.0
        xcode_destination: platform=tvOS Simulator,OS=12.0,name=Apple TV
        xcode_scheme: BrickApp-tvOS

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BrickKit' -X xcodeplist
